{% set name = "doctest" %}
{% set version = "2.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/onqtam/doctest/archive/{{ version }}.zip
    sha256: 2819d59d60ca78403da5dfbda7153a23ea5da73776cd6e49bf407d2dff78f4dd

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - ninja

test:
  commands:
    - test -f $PREFIX/include/doctestdoctest.h                               # [unix]
    - test -f $PREFIX/lib/cmake/doctest/doctestConfig.cmake                  # [unix]
    - if not exist %LIBRARY_INC%\\doctest\\doctest.h exit 1                  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\doctestConfig.cmake exit 1  # [win]

about:
  home: https://github.com/onqtam/doctest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The fastest feature-rich C++11/14/17/20 single-header testing framework for unit tests and TDD

  description: |
    doctest is a new C++ testing framework but is by far
    the fastest both in compile times (by orders of magnitude) and
    runtime compared to other feature-rich alternatives.
    It brings the ability of compiled languages such as D / Rust / Nim to
    have tests written directly in the production code thanks to a fast,
    transparent and flexible test runner with a clean interface.
  doc_url: https://github.com/onqtam/doctest/blob/master/doc/markdown/readme.md#reference
  dev_url: https://github.com/onqtam/doctest

extra:
  recipe-maintainers:
    - elbaro
 